### ISSUE TITLE
Tag release/melodic/apriltag/3.1.2-1 no longer in release/melodic/apriltag branch

### ISSUE THREAD

**Issue by shr-project** [AprilRobotics/apriltag-release#1]
I believe it was included there before, but now this tag doesn't exist in any branch:
```
$ git branch -a --contains 17a996455fc2cad7546e716fc45fe10fb92074c5
$
```

```
$ git log --oneline 17a996455fc2cad7546e716fc45fe10fb92074c5
17a9964 (tag: release/melodic/apriltag/3.1.2-1) Set libdir to lib
b5d0b79 Rebase from 'upstream'
864b8c8 Set libdir to lib
07eda2a Rebase from 'upstream'
ebb2f34 (release/melodic/apriltag) Set libdir to lib
4db996f (tag: release/melodic/apriltag/3.1.1-1) Rebase from 'upstream'
```

**Comment by wxmerkt** [comment]
Thanks - I am not quite sure what caused this. It should be fixed by releasing a new version, no? Or what is the suggested action to address this?

**Comment by shr-project** [comment]
@wxmerkt sorry I have no experience with bloom release process, my naive fix would be to update the release/melodic/apriltag branch to contain release/melodic/apriltag/3.1.1-1 tag (either by merging it or rebasing on top of it, which looks like it should result in fast-forward for both).

But this might fix only one symptom of what went wrong during previous release (and then it might be worth investigating it to find what else might need fixing).

I've added work around for this in meta-ros for now.
